---
apiVersion: v1
kind: Service
metadata:
  name: devops-tech-challenge
  labels:
    app: devops-tech-challenge
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  ports:
    - name: http
      port: 3000
  clusterIP: None
  selector:
    app: devops-tech-challenge
